---
- include_tasks: debian/pkg.yml
  tags: monit_pkg
  when: ansible_os_family == "Debian"

- include_tasks: redhat/pkg.yml
  tags: monit_pkg
  when: ansible_os_family == "RedHat"

- include_tasks: binary/pkg.yml
  tags: monit_binary

- include_tasks: config.yml
  tags: monit_config

- include_tasks: monitors.yml
  tags: monit_monitors
